# ===== Servidor =====
server.port=8080
spring.application.name=transacciones

# ===== Conexion a Supabase PostgreSQL (Session Pooler / IPv4) =====
spring.datasource.url=jdbc:postgresql://<cambiar-a-tu-supabase>/postgres
spring.datasource.username=<tu-usuario-supabase>
spring.datasource.password=<tu-password>
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== HikariCP (pool de conexiones) =====
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

